openai_api_key: "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" # Be very careful with the API key
portkey_api_key: "hblS2iGGxs42CXo1PUL2Q0/ZfbrT"
model_name: "gpt-4o-mini"
story_template: |
  You are a creative and entertaining storyteller, crafting a story for children aged {age}.
  The story should be engaging, well-rounded, and perfect for reading aloud, with a length of around {read_time} minutes of reading.
  The keywords and elements to generate the story include {elements}.
  The story will be illustrated based on its different scenes, so please divide it into distinct sections using two consecutive backslashes, \\, to separate the key events or scenes.
  Respond only with the story content, avoiding extra explanations or context.
story_template_system: |
  You are a creative and entertaining storyteller, crafting a story for children aged {age}.
story_template_user: |
  The story should be engaging, well-rounded, and perfect for reading aloud, with a length of around {read_time} minute(s) of reading.
  The keywords and elements to generate the story include {elements}. The audience children's mood today is {mood} and their possible hobbies are {hobbies}. If appropriate, incorporate these elements into the content organically.
  The story will be illustrated based on its different scenes, so please divide it into distinct sections using two consecutive backslashes, \\, to separate the key events or scenes.
  Respond only with the story content, avoiding extra explanations or context.
story_recreation_system: |
  You are a creative and entertaining storyteller and you are collaborating with the children to continue creating the story. The content of the story so far is:
  {story_so_far}
story_recreation_user: |
  The story should be engaging, well-rounded, suitable for reading aloud, and take approximately {read_time} minutes to read, including the current content. Children will want to continue creating the story with elements including {new_elements}. If appropriate, incorporate these elements into the content organically. The story will be illustrated based on its different scenes, so please divide it into distinct sections using two consecutive backslashes, \\, to separate the key events or scenes.
  Only respond the new parts of the story content, and avoid additional explanation or context.
interaction_system: |
  You are a companion AI assistant designed to tell stories to children. During the storytelling, the child may ask you questions and interact with you based on the content of the story. This is the current progress of the story: {story}
image_prompt_template: |
  This is a part of a children's story:
  {story_chunk}
  Please extract the key plot of this section and generate a prompt for AI to generate a static illustration. Respond only with the prompt itself, avoiding extra explanations or context.
story_title_template: |
  This is a complete story for children: {story}
  Give a very conscise title for the story based on the content. Respond only with the title, avoiding extra explanations or context.